try:
    raise
except:
    print("Errorが出ました")
finally:
    print("実行を終了します")